ALTER TABLE tests ALTER COLUMN status DROP DEFAULT;
ALTER TABLE questions ALTER COLUMN question_type DROP DEFAULT;

ALTER TABLE tests ALTER COLUMN status TYPE VARCHAR(20);
ALTER TABLE questions ALTER COLUMN question_type TYPE VARCHAR(20);

DROP TYPE IF EXISTS test_status CASCADE;
DROP TYPE IF EXISTS question_type CASCADE;
