name: Build & Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'README.md'
      - 'API_DOCUMENTATION.md'
      - 'docs/**'
      - '**/*.md'
      - '**/*.mdx'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'README.md'
      - 'API_DOCUMENTATION.md'
      - 'docs/**'
      - '**/*.md'
      - '**/*.mdx'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: fakhri2406/qanun-qapisi:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Contabo via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/qanun-qapisi
            docker compose pull app
            docker compose up -d
